### ISSUE TITLE
(node:54728) DeprecationWarning: Using Buffer without `new` will soon stop working.

### ISSUE THREAD

**Issue by agopshi** [brianc/node-buffer-writer#9]
```
$ node --trace-deprecation baz 
(node:54728) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
    at Buffer (buffer.js:79:13)
    at new module.exports (/Users/foo/bar/node_modules/buffer-writer/index.js:6:17)
    at new Connection (/Users/foo/bar/node_modules/pg/lib/connection.js:29:17)
    at new Client (/Users/foo/bar/node_modules/pg/lib/client.js:34:37)
    at Object.<anonymous> (/Users/foo/bar/baz.js:8:11)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

The fix is a very simple change on `index.js`, line 5, from:
```
  this.buffer = Buffer(this.size + 5);
```
To:
```
  this.buffer = Buffer.alloc(this.size + 5);
```

**Comment by brianc** [comment]
Closed with #10
